kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ClusterRole }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "update", "create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ServiceAccount }}
  namespace: kube-system
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.Binding }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccount }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ .Values.ClusterRole }}
  apiGroup: rbac.authorization.k8s.io
